# ── Helium Dashboard — Static Web Server ────────────────────────────────────
# Serves the research dashboard (index.html + data.json) with nginx.
#
# Build & run:
#   cd scraper/dashboard
#   docker build -t helium-dashboard .
#   docker run --rm -p 8080:80 helium-dashboard
#
# Then open http://localhost:8080
#
# To use live data from the host (regenerated by the scraper):
#   docker run --rm -p 8080:80 \
#     -v $(pwd):/usr/share/nginx/html:ro \
#     nginx:alpine
# ─────────────────────────────────────────────────────────────────────────────

FROM nginx:alpine

# Copy dashboard files into nginx's default serve directory
COPY index.html /usr/share/nginx/html/index.html
COPY data.json  /usr/share/nginx/html/data.json

# Minimal nginx config: serve static files, disable server_tokens for security
RUN printf 'server {\n\
    listen 80;\n\
    root /usr/share/nginx/html;\n\
    index index.html;\n\
    server_tokens off;\n\
    add_header X-Frame-Options SAMEORIGIN;\n\
    add_header X-Content-Type-Options nosniff;\n\
    location / { try_files $uri $uri/ =404; }\n\
    location ~* \\.json$ { add_header Cache-Control "no-cache"; }\n\
}\n' > /etc/nginx/conf.d/default.conf

EXPOSE 80
